server:
    port: 3001
    error:
        include-message: always

# debug: true
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sigdb
        username: postgres
        password: 12345678
    jpa:
        hibernate:
            ddl-auto: validate

    application:
        name: sig
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 1024MB
            max-request-size: 1024MB
        

sig:
    openapi:
        prod-url: http://localhost:3001
        dev-url: http://localhost:3001
        url: http://localhost:3001
    
data:
    image: /src/main/resources/image
